name: Draft a new release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  create-draft-release:
    runs-on: ubuntu-latest
    steps:
      ######################################################################
      # get the tag name
      ######################################################################
      - name: ğŸ· Get tag from the push
        id: set_varaibles
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      ######################################################################
      # create a new draft release
      ######################################################################
      - name: ğ–­¦ Create new draft release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #with:
         # tag_name: ${{ steps.set_varaibles.outputs.tag }}
          #release_name: v${{ steps.set_varaibles.outputs.tag }}
          #body: ${{ github.event.head_commit.message }}
          #draft: true
          #prerelease: false
